### PR TITLE
Implemented openal

### PR DESCRIPTION
**Pull request by ThuCommix**
Note that openal needs some adjustments to match the unit tests

### CODE REVIEW

**Comment by ThuCommix** [comment]
I may should allow the user to specify the device by himself. Also the device incl. context should be initialized in the constructor so it's less error-prone. Will do this today somewhere in the evening.

**Comment by filoe** [comment]
Would be nice!

**Comment by ThuCommix** [comment]
Done. I guess it's ready for review.

**Comment by filoe** [comment]
I've had a look a few weeks ago (just before my holiday :) ). Unfortunately I was not able to playback a simple track. Since I would love to have OpenAL as part of CSCore, could you please have a another look at it? If it would be able to play tracks, I could take a look at it and make it fit to the specifications of the unittests.

**Comment by SplittyDev** [comment]
@filoe Could you provide some information on why your weren't able to play a track using OpenAL?

**Comment by filoe** [comment]
Try it out, it is just some kind of "crackle" sound.

**Comment by filoe** [comment]
New version available. See #93.

**Pull request closed without merging**
